croberts27/recyculator

index.html

added footer elements with some text

Create footer outline

---

index.html
style.css

initial CSS framing added

---

index.html

adds the following code into the aside element:
<input class="input is-primary" type="text" placeholder="What can I do with...">
<button class="button is-primary">Search</button>

adds styling for input and search button

---

assests/style.css
index.html

adds two tiles to the top section for information, and a larger tile on the bottom to hold the map

adds three tiles to the main section

---

assests/scripts/script.js
assests/style.css
index.html

I added a getLocation function to have user grant access to location (lon, lat) on page load. 
I added a modal for user to input zip code. 
still need to have this saved in local storage.
I also re-ordered the "welcome to the recyculator" message to be in the navbar so the zip code modal can be beneath that in the heading.

44 create modal to get user location data

---

assests/scripts/location.js
assests/scripts/script.js
index.html

created location.js for geolocation/local storage js to live

create JS file 

---

index.html

Changed footer through deleting placeholders.
Open html to see placeholders are deleted.
Make sure it doesn't look broken when you open it!

67 footer changed

---

assests/scripts/script.js
index.html

increases readability of the code by adding comments
sets a roadmap for the search button event listener

adds comments to HTML and JS around the search input and button

---

assests/scripts/location.js
index.html

user location fixed

---

assests/scripts/location.js

79 save user location in local storage

---

assests/scripts/script.js
index.html

To test the functionality, type an item into the search bar and click the search button. The search should appear in the green tile. Enter a new search item and click 'search'. The old text should disappear in the green tile and the new search should appear

clears div text content when a new search is made

---

assets/news.css
assets/news.html

- created framework for news page
- added navbar with links
- created three tiles where the news articles can live
- added a footer

98 html framework for news page

---

assets/news.html
assets/scripts/news.js

"added api key and dependencies to news.js"

add api key to news page

---

index.html

Open the HTML to see the yellow tile on the left side

replaces buttons with tile on the left side

---

assets/scripts/script.js

Open HTML to see that the scrolling content has moved to the left-hand side

moves scroll content to the left tile

---

assets/style.css
index.html

removed code for zip code box in HTML and CSS

zip code box removal

---

assets/style.css
index.html

finished the height and width after we changed the deployed version back

finalized logo

---

assets/scripts/script.js
index.html

enter a search request from the drop-down list. When you click the search button, the title and content should give information about how to recycle that item

95 style recycle information as card

---

assets/style.css
index.html

updated css to allow heading to resize with screen change

136 fix the navbar to ensure mobile friendly and all items size together

---

assets/scripts/script.js

Search for an item that is not included in our array, and the card will show the item and direct the user to the resource page to continue their search

adds text for searches that are not in our array

---

assets/news.html
assets/scripts/news.js

added fetch request to pull data using media API and used then statements to feed the data back into  HTML elements
IMPORTANT: only works when live server is enabled

config news api

---

assets/style.css
index.html

Enter a search item and click the search button. The styled text will appear in the green box, and the box size will respond to the amount of text

styles the green card (removes white box)

---

assets/scripts/script.js
index.html

This adds a button to the resources page when a user searches for an item that is not in our array.
To test, search for 'toys', 'clothes', or anything else that isn't part of our drop-down list. The placeholder should appear with a yellow button at the bottom. Click the button and you should be taken to the resources page

154 link green card placeholder to resources page

---

assets/scripts/script.js
index.html

When you search for an item, you should see two sections: "how to recycle", and "alternatives to recycling"

adds alternatives to recycling within the green tile

---

README.md
assets/news.html
assets/scripts/news.js

resolved this by finding an api that shouldn't require any HTTPs work arounds.
updated README with credits

news api https error

---

assets/scripts/news.js

changed index to pull a more relevant article

news api update

---

index.html

When you load the page you should see text in the blue box

adds a template for local recycling display

---

assets/style.css
index.html

When you search for an item, the "how to recycle" and "alternative to recycling" headers are more evident on the page

changes the color of h3 elements to make them stand out on the page

---

assets/news.html
assets/resources.css
assets/resources.html

added resource links to resource page and styled accordingly

resource page links

---

assets/scripts/script.js
index.html

added JS function to clear name/email input fields when user clicks 'submit' to give the illusion that we are saving their inputs

clear name/email input fields

---

assets/style.css

the footers top that shows the number of recyculators 'become a recyculator' today was disappearing.  fixed this by increasing padding to 2 rem 2.5rem 6rem.

adds some additional padding to footer to ensure it shows

---

index.html

incresed logo height

---

README.md
assets/scripts/location.js
index.html

This handles the blue box and includes the name and address from the google API

191 nice to have feature welcome back user when they reload the page
